Documentation
Nibuja05/spinners_ts pull request #10
Opened 2021-04-06 17:17 UTC by Nibuja05

added documentation string to most commonly used functions including:

- `weapon_functions`
- `util`, also now gathered under namespace `Util`
- `arena`
- `game_mode_manager`
- `weapon_base`

Also various fixes:
- Arena is now `PlayerArena` and strictly assigned to an owner
- WaveManager now also respects multiple player
- fixed Lasers not working
- fixed issues with modifiers after death

2021-04-06 19:56 UTC, Shushishtok reviewed
Does it knows to find the specific "throne backplate" of the specific arena, assuming there's more than one in the map?

2021-04-06 21:39 UTC, Shushishtok requested changes

2021-04-06 21:39 UTC, Shushishtok commented on game/scripts/vscripts/core/weapon_base.ts
> + */
Consider adding setters to all getters that we have. Just in case we'll need them.

2021-04-06 21:39 UTC, Shushishtok commented on game/scripts/vscripts/core/weapon_base.ts
> +	 * @returns
Fill the return with `returns whether the projectile should disappear on impact - relevant only for linear projectiles`.

2021-04-06 21:39 UTC, Shushishtok commented on game/scripts/vscripts/core/weapon_functions.ts
> + * @param args paramater table for modifier creation (can use complex types!)
What kind of complex type? Can you expand on that in the documentation? Maybe as an example?

2021-04-06 21:39 UTC, Shushishtok commented on game/scripts/vscripts/core/weapon_functions.ts
>  	const time = duration || 0.5;
I suggest replacing `||` with the `??` operator. Here is an explanation what's the difference:
https://indepth.dev/posts/1300/double-question-marks-typescript-3-7-nullish-coalescing

2021-04-06 21:39 UTC, Shushishtok commented on game/scripts/vscripts/core/weapon_functions.ts
>  			tickSpeed: tick,
Is tick equaling 0.01 instead of FrameTime() a good idea here?

2021-04-06 21:39 UTC, Shushishtok commented on game/scripts/vscripts/core/weapon_functions.ts
> +		let arena = Arena.GetPlayerArena(this.caster as CDOTA_BaseNPC_Hero);
Define `this.caster` as type CDOTA_BaseNPC_Hero so you won't have to do it inside the code, like in this line.

2021-04-06 21:39 UTC, Shushishtok commented on game/scripts/vscripts/core/weapon_functions.ts
> + * @param referenceUnit its forward direction determines the laser direction
Could you please expand the description of CreateNewLaser? Most params have no explanation attached to them. For referenceUnit, isn't it usually the caster or the weapon (are weapons CDOTA_BaseNPC?)? Would it be something else that determines the direction, like an enemy?

2021-04-06 21:39 UTC, Shushishtok commented on game/scripts/vscripts/core/weapon_functions.ts
>  	auraRadius: number = 200;
Hardcoded: please add a get/set of this value and private it.

2021-04-06 21:39 UTC, Shushishtok commented on game/scripts/vscripts/core/weapon_functions.ts
> +	// OnCreated(event: {effect: string}) {
If they are not relevant, please remove those lines.

2021-04-06 21:39 UTC, Shushishtok commented on game/scripts/vscripts/core/weapon_functions.ts
>  		this.StartIntervalThink(1/60);
Is this interval think intended to be hardcoded, or would it be sensible to make it something that can be get/set?

2021-04-06 21:39 UTC, Shushishtok commented on game/scripts/vscripts/core/weapon_functions.ts
>  		if (distance > this.width) {
Can change those to `return distance > this.width` for readability.

2021-04-06 21:39 UTC, Shushishtok commented on game/scripts/vscripts/lib/manual_interface_declarations.ts
> +// interface CDOTABaseGameMode
If we don't need it, remove it.

2021-04-06 21:39 UTC, Shushishtok commented on game/scripts/vscripts/lib/util.ts
> +	export function GetRandomElement<T>(arr:T[]):T {
Since this isn't a "game element" (e.g. water), maybe the description should be made to better reflect that? I was sure it was an actual element, out of a few random elements.

2021-04-06 21:39 UTC, Shushishtok commented on game/scripts/vscripts/lib/util.ts
> +			return [arr[RandomInt(0, arr.length - 1)]];
I'm seeing `RandomInt(0, arr.length - 1)` being repeated multiple times on Util functions. Maybe make a Util function: `GetRandomElementFromArray` that does that instead? Reduces the chance to have a mistake.

2021-04-06 21:39 UTC, Shushishtok commented on game/scripts/vscripts/lib/util.ts
> +	export function FindUnitsInCone(team: DotaTeam, cacheUnit: CBaseEntity | undefined, teamFilter: UnitTargetTeam, typeFilter: UnitTargetType,
I've never seen cacheUnit being used on a FindUnitsInX; can we assume it is simply `undefined`?

2021-04-06 21:39 UTC, Shushishtok commented on game/scripts/vscripts/lib/util.ts
> +	function coneWidth(distance: number, angle: number) {
Add documentation please.

2021-04-06 21:39 UTC, Shushishtok commented on game/scripts/vscripts/weapons/basic_electricity.ts
>  		let maxAngle = 70;
maxAngle should also be taken from GetSpecialValueFor, imo.

2021-04-06 21:39 UTC, Shushishtok commented on game/scripts/vscripts/weapons/basic_electricity.ts
> +			damage_type: DamageTypes.MAGICAL,
Do we have resistances? 
Regardless, we should call `this.GetAbilityDamageType()` instead and not hardcode damage types.

2021-04-06 21:39 UTC, Shushishtok commented on game/scripts/vscripts/weapons/basic_fire.ts
>  			// DebugDrawCircle(loc, Vector(0,255,0), 0, 100, false, 2);
Remove if no longer relevant.

2021-04-06 22:02 UTC, Nibuja05 commented on game/scripts/vscripts/core/arena.ts
> +		let corner1 = Entities.FindByName(undefined, "corner_1")!;
these changes will be made once the new map is built.

2021-04-06 22:05 UTC, Nibuja05 commented on game/scripts/vscripts/lib/util.ts
> +	function coneWidth(distance: number, angle: number) {
it is not exported and only used internally, should I still add a documentation?

2021-04-06 22:05 UTC, Nibuja05 commented on game/scripts/vscripts/weapons/basic_electricity.ts
>  		let maxAngle = 70;
true

2021-04-06 22:06 UTC, Nibuja05 commented on game/scripts/vscripts/weapons/basic_electricity.ts
> +			damage_type: DamageTypes.MAGICAL,
there is no GetAbilityDamageType() :/
either we need to move it into the weapon data file (KV/TS) or define it somewhere else

2021-04-06 22:08 UTC, Nibuja05 commented on game/scripts/vscripts/core/arena.ts
> +		CustomGameEventManager.Send_ServerToAllClients("show_speech_bubble", {
unsure about that one. The Kobold can only say one thing at the same time, right?
The speech bubble gets placed in world coordinates, so if other non-relevant players aren't looking there they won't see it. Also it could be kinda cool to see what the Kobold says to others?
But generally unsure how to handle it

2021-04-07 20:16 UTC, Nibuja05 commented on game/scripts/vscripts/core/arena.ts
> +		this.corners = [
done

2021-04-07 20:17 UTC, Nibuja05 commented on game/scripts/vscripts/core/arena.ts
> +	GetArenaOwner() {
done

2021-04-07 20:17 UTC, Nibuja05 commented on game/scripts/vscripts/core/arena.ts
> +	export function GetPlayerArena(hero: CDOTA_BaseNPC_Hero) {
done

2021-04-07 20:17 UTC, Nibuja05 commented on game/scripts/vscripts/lib/util.ts
> +	export function FindUnitsInCone(team: DotaTeam, cacheUnit: CBaseEntity | undefined, teamFilter: UnitTargetTeam, typeFilter: UnitTargetType,
done

2021-04-07 20:17 UTC, Nibuja05 commented on game/scripts/vscripts/lib/util.ts
> +	function coneWidth(distance: number, angle: number) {
still done

2021-04-07 20:18 UTC, Nibuja05 commented on game/scripts/vscripts/weapons/basic_electricity.ts
>  		let maxAngle = 70;
done

2021-04-07 20:19 UTC, Nibuja05 commented on game/scripts/vscripts/weapons/basic_electricity.ts
> +			damage_type: DamageTypes.MAGICAL,
added `GetAbilityDamageType()` to the base weapon, so its there.
Default Value is still magic damage, but can be changed easily now

2021-04-07 20:19 UTC, Nibuja05 commented on game/scripts/vscripts/weapons/basic_fire.ts
>  			// DebugDrawCircle(loc, Vector(0,255,0), 0, 100, false, 2);
?

2021-04-07 23:53 UTC, Nibuja05 commented on game/scripts/vscripts/core/game_mode_manager.ts
> +		let player = PlayerResource.GetPlayer(playerID)!;
Its for the starting conversation, its currently disabled since it takes very long each start

2021-04-08 15:52 UTC, Nibuja05 commented on game/scripts/vscripts/core/weapon_functions.ts
>  	auraRadius: number = 200;
doesnt need a setter, width is determining the actualy search width, only for placing dummy units.
Also gets redefined later

2021-04-08 15:53 UTC, Nibuja05 commented on game/scripts/vscripts/core/weapon_functions.ts
>  		this.StartIntervalThink(1/60);
no, making a setter for an interval is not needed. The value should always stay the same: changing it makes no difference (other than smoothness)

2021-04-08 16:12 UTC, Shushishtok approved these changes

2021-04-08 16:12 UTC, merged