KV -> TS
Nibuja05/spinners_ts pull request #14
Opened 2021-04-11 19:28 UTC by Shushishtok

Fixes https://github.com/Nibuja05/spinners_ts/issues/6

Includes a TON of stuff:
- waves.kv and presets.kv were removed (weapons.kv remains, for now I don't have an issue with it being a KV since it's only used for GetAbilitySpecialFor)
- Waves are now initiated by the WaveManager and are defined by Typescript. Has the function `GetWaveDefinitionByIndex` which accepts the wave number and returns the appropriate wave definition.
- Presets are now initiated by the GameMode and are defined by Typescript. Presets have a few functions for getting all or part of them.
- Fixed an issue with the laser triggering deaths for dummies in the wave triggers.
- Added some errors around for error handling of unexpected issues.
- Moved all the interfaces and most of the enums to the /root/common folder in the d.ts, and vscript/panorama now can see them. We might want to split those to more files because `general.d.ts` is huge. Events can now be seen by both sides.

2021-04-12 23:09 UTC, Nibuja05 requested changes
Changes looking really good so far! Testing also showed no prblems so far :)

I noticed that you used a lot of spaces instead of tabs. This makes some files very inconsistent in terms of identation. Could you please change the identation of all stuff you worked on to tabs instead of spaces? This is a general concern, so I didn't marked all occurances

2021-04-12 23:09 UTC, Nibuja05 commented on game/scripts/vscripts/lib/util.ts
> +    export function IsDummyUnit(unit: CDOTA_BaseNPC) {
please use tabs instead of spaces

2021-04-12 23:09 UTC, Nibuja05 commented on game/scripts/vscripts/core/game_mode_manager.ts
> +    function ShowPresets(playerID: PlayerID) {
A lot of prints here. Do we need all of them?

2021-04-13 06:53 UTC, Shushishtok commented on common/general.d.ts
> +interface CDOTABaseGameMode {
Removed.

2021-04-13 06:53 UTC, Shushishtok commented on common/general.d.ts
> +interface CDOTA_BaseNPC {
Removed.

2021-04-13 06:54 UTC, Shushishtok commented on common/general.d.ts
> +declare const enum PresetName {
Moved to presets.d.ts in the same folder.

2021-04-13 06:56 UTC, Shushishtok commented on common/general.d.ts
> +declare const enum WaveName {
Moved to waves.d.ts

2021-04-13 06:57 UTC, Shushishtok commented on common/general.d.ts
> +declare const enum WeaponName {
Moved to weapons.d.ts.

2021-04-13 07:16 UTC, Shushishtok commented on content/panorama/scripts/custom_game/weapon_base.ts
>  function GetElementName(element: WeaponElement):string {
Fixed. Elements are now localized by a string representing them.

2021-04-13 07:39 UTC, Shushishtok commented on game/scripts/vscripts/lib/util.ts
> +    export function IsDummyUnit(unit: CDOTA_BaseNPC) {
Installed Prettier (you should run `npm install`, then `npm run init`). This auto formatted all of our files with tabs instead of spaces. Configured it to automatically format on save as well.

2021-04-13 07:40 UTC, Shushishtok commented on game/scripts/vscripts/core/wave_manager.ts
> +        Waves.Init();
Moves to GameMode.ts.

2021-04-13 07:41 UTC, Shushishtok commented on game/scripts/vscripts/core/game_mode_manager.ts
> +    function ShowPresets(playerID: PlayerID) {
Removed all prints.

2021-04-13 15:27 UTC, Nibuja05 approved these changes
Looks good!

2021-04-13 15:28 UTC, merged