Versus map
Nibuja05/spinners_ts pull request #23
Opened 2021-04-13 17:03 UTC by Nibuja05

Fixes #11 

Added new map: `versus_arena`, use `dota_launch_custom_game spinners_ts versus_arena` to lauch this map.
Adjusted huge parts of `arena.ts` and did according changes in other files.

Still to do for later:
- Teams

2021-04-13 20:41 UTC, Shushishtok requested changes

2021-04-13 20:41 UTC, Shushishtok commented on .gitignore
> +content/AssetBrowserSavedSearches.kv3
I assume you wanted to gitignore it but the file still made it in ;p

2021-04-13 20:41 UTC, Shushishtok commented on game/scripts/vscripts/core/arena.ts
> +	let arenas: { [playerIndex: string]: PlayerArena } = {};
Maybe it would be easier to use a map? 
`arenas: Map<playerID, PlayerArena> = new Map()`
It would be very easy to use it to find the arena of the player, by simply using `arenas.get(playerID)`.

2021-04-13 20:41 UTC, Shushishtok commented on game/scripts/vscripts/core/arena.ts
> +		AddFOWViewer(team, this.center, 2000, 9999, true);
I think it would be easier to completely remove fog of war from this game using `SetFogOfWarDisabled(true)`. AddFOWViewers are known to drain performance.

2021-04-13 20:41 UTC, Shushishtok commented on game/scripts/vscripts/core/arena.ts
> +		super("a" + arenaIndex);
Any chance we can improve the naming of those so they won't just be "a1", for instance?
Same for barriers.

2021-04-13 20:41 UTC, Shushishtok commented on game/scripts/vscripts/core/triggers.ts
> +//  */
Remove comments from.. comments. xD

2021-04-13 20:41 UTC, Shushishtok commented on game/scripts/vscripts/core/triggers.ts
> +//  */
Remove comments from.. comments. xD

2021-04-13 22:39 UTC, Nibuja05 commented on .gitignore
> +content/AssetBrowserSavedSearches.kv3
yeah it was added before

2021-04-13 22:39 UTC, Nibuja05 commented on game/scripts/vscripts/core/arena.ts
> +	let arenas: { [playerIndex: string]: PlayerArena } = {};
how is it different?

2021-04-13 22:40 UTC, Nibuja05 commented on game/scripts/vscripts/core/arena.ts
> +		AddFOWViewer(team, this.center, 2000, 9999, true);
ohhh, probably true...

2021-04-13 22:40 UTC, Nibuja05 commented on game/scripts/vscripts/core/arena.ts
> +		super("a" + arenaIndex);
don't want to do it. Its manually renaming and and suuuper tedious

2021-04-14 10:26 UTC, Shushishtok approved these changes

2021-04-14 10:26 UTC, merged